language: go
sudo: required
install: true
go:
  - 1.8.x
  - master
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.8
    - IMAGE_NAME=tsuru/api
addons:
  apt:
    packages:
      - rsyslog
      - xmlsec1
      - rpm
before_script:
  - rsyslogd &
  - sleep 1
before_install:
  - git fetch --unshallow || true
  - sleep 15
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
  - sudo ifconfig
  - sudo sysctl -a | grep ipv6.conf
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get -qq update
  - sudo apt-get install -y mongodb-org
  - sudo service mongod start || true
  - service mongod status
  - go env && pwd
jobs:
  include:
    - stage: test
      script: make test
    - stage: lint
      script: if [ "${TRAVIS_EVENT_TYPE}" = "push" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then make lint; else make metalint; fi
    - stage: lint-handlers
      script: ./misc/check-handlers.sh
    - stage: lint-events
      script: ./misc/check-events.sh
    - stage: lint-check-docs
      script: make check-api-doc
    - stage: build
      script: CGO_ENABLED=0 go build -ldflags "-X github.com/tsuru/tsuru/cmd.GitHash=`git rev-parse HEAD`" ./cmd/tsurud/
    - stage: deploy-docker-image
      script: curl https://raw.githubusercontent.com/tsuru/push-to-docker/master/push.sh | bash
    - stage: deploy-packages
      script:
        - git clean -dfx
        - test -n "$TRAVIS_TAG" && curl -sL https://raw.githubusercontent.com/tsuru/push-to-packagecloud/master/push.sh | PACKAGE_NAME=tsuru-server bash
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: QJe4k18ACRUP4CDo245vBFu1hpVlcR3JPWjT7NL/vAE/Y5KDn5pNXIREPYIx9F/f8lvjF2RrQxjApeUujRh1PPt2Q53JulvaDCfM5a5SYnk5yoqu3ynlfqU4AOTDa6kzoJ3K4M9X8JhMpOtr3+IOPbwV88FjPvwviZN4p0L/0wc=
services:
  - redis
  - docker
  - mongodb
matrix:
  allow_failures:
    - go: master
